apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/cert-manager-operator-release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && ( "catalogs/v4.18/***".pathChanged() || ".tekton/cert-manager-operator-index-4-18-pull-request.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cert-manager-operator-index-4-18
    appstudio.openshift.io/component: cert-manager-operator-index-4-18
    pipelines.appstudio.openshift.io/type: build
  name: cert-manager-operator-index-4-18-on-pull-request
  namespace: cert-manager-oape-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/cert-manager-oape-tenant/cert-manager-operator-4-18/cert-manager-operator-index-4-18:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Containerfile
  - name: path-context
    value: catalogs/v4.18
  - name: build-args
    value: []
  pipelineRef:
    name: fbc-build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-cert-manager-operator-index-4-18
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
